dist: bionic

language: python

python:
  - 3.7

git:
  depth: 3

branches:
  only:
    - master

notifications:
  email: false

# Install packages
install:
  - apt-get install python-dev libpython-dev
  - pip install cython
  - pip install -r requirements.txt
  - ./setup.py build install
  - pip install -r test-requirements.txt

# Run test
script:
  - ./setup.py test

after_success:
  - bash <(curl -s https://codecov.io/bash)
