#!/usr/bin/env bash

set -e -o pipefail

##################################################################
CWD=$(dirname $(dirname $(realpath $0)))
DATA_DIR=$CWD/data

##################################################################
# methods: ddr last lcrf lmcrf rdp r2n2 root wang
# relschemes: chenlo heerschop zhou pcc
# base classifiers: hu-liu mohammad lba
# corpus: PotTS SB10k
for method in ddr last lcrf lmcrf rdp r2n2 root wang; do
    for base_classifier in hu-liu mohammad; do
	for corpus in PotTS SB10k; do
	    echo "${method} ${base_classifier} ${corpus}" >&2
	    log_file="${CWD}/${method}.${base_classifier}.${corpus}.log"
	    train_data=${DATA_DIR}/$corpus/train/*.json
	    dev_data=${DATA_DIR}/$corpus/dev/*.json
	    test_data=${DATA_DIR}/$corpus/test/*.json
	    output_file=${DATA_DIR}/$corpus/predicted/$method/$method.$base_classifier.json
	    # train
	    dasa_sentiment train -t $method -r bhatia -s $base_classifier \
			   $train_data $dev_data &> "${log_file}"
	    # test
	    dasa_sentiment test $test_data > $output_file 2>> "${log_file}"
	done
    done
done
